package com.example.inr_management_md3.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF008cb4)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFbce9ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001f2a)
val md_theme_light_secondary = Color(0xFFCBF0FF)
val md_theme_light_onSecondary = Color(0xFF001f2a)
val md_theme_light_secondaryContainer = Color(0xFFCBF0FF)
val md_theme_light_onSecondaryContainer = Color(0xFF081e27)
val md_theme_light_tertiary = Color(0xFF745b00)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFeadebd)
val md_theme_light_onTertiaryContainer = Color(0xFF241a00)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfcfe)
val md_theme_light_onBackground = Color(0xFF191c1e)
val md_theme_light_surface = Color(0xFFfbfcfe)
val md_theme_light_onSurface = Color(0xFF191c1e)
val md_theme_light_surfaceVariant = Color(0xFFdce3e8)
val md_theme_light_onSurfaceVariant = Color(0xFF40484c)
val md_theme_light_outline = Color(0xFF70787d)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1f3)
val md_theme_light_inverseSurface = Color(0xFF2f3132)
val md_theme_light_inversePrimary = Color(0xFF65d3ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF007090)
val md_theme_dark_onPrimary = Color(0xFFffffff)
val md_theme_dark_primaryContainer = Color(0xFF004d66)
val md_theme_dark_onPrimaryContainer = Color(0xFFbce9ff)
val md_theme_dark_secondary = Color(0xFFb7d8ff)
val md_theme_dark_onSecondary = Color(0xFF1f333c)
val md_theme_dark_secondaryContainer = Color(0xFF354a54)
val md_theme_dark_onSecondaryContainer = Color(0xFFd0e6f3)
val md_theme_dark_tertiary = Color(0xFFe9c349)
val md_theme_dark_onTertiary = Color(0xFF3d2f00)
val md_theme_dark_tertiaryContainer = Color(0xFFd6be7d)
val md_theme_dark_onTertiaryContainer = Color(0xFF574400)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1e)
val md_theme_dark_onBackground = Color(0xFFe1e2e4)
val md_theme_dark_surface = Color(0xFF191c1e)
val md_theme_dark_onSurface = Color(0xFFe1e2e4)
val md_theme_dark_surfaceVariant = Color(0xFF40484c)
val md_theme_dark_onSurfaceVariant = Color(0xFFc0c7cc)
val md_theme_dark_outline = Color(0xFF8a9297)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1e)
val md_theme_dark_inverseSurface = Color(0xFFe1e2e4)
val md_theme_dark_inversePrimary = Color(0xFF006685)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF008cb4)
val error = Color(0xFFba1b1b)
val Custom0 = Color(0xFF36C84B)
val Custom1 = Color(0xFFFDBC40)
val Custom2 = Color(0xFFFC5753)
